### ISSUE TITLE
Strange code for DeviceStrategy

### ISSUE THREAD

**Issue by jmalak** [eduardocasino/dos-device-driver#2]
I am not sure what you are trying to achive by DeviceStrategy function, but it is generaly wrong.

```
void __declspec(naked) far DeviceStrategy( void )
{
    __asm {
        mov     word ptr cs:[fpRequest], bx
        mov     word ptr cs:[fpRequest+2], es
        retf
    }
}
```

What es:bx is? 
In C code it is random, not guarantie value.
I thing it should be something like

```
static void _device_strategy( void far *req );
#pragma aux _device_strategy = \
        "mov     word ptr cs:[fpRequest], bx" \
        "mov     word ptr cs:[fpRequest+2], es" \
     parm [es bx]

void far DeviceStrategy( void far *req )
{
    _device_strategy( req );
}
```

anyway you can use fpRequest directly in C code and need not to use DeviceStrategy at all.
it is enough if you define fpRequest as
```
#define CODE_BASED    __based(segname("_CODE"))
static request far * CODE_BASE fpRequest = (request far *)0;
```

this way you can define other variables located in code segment to be accessible directly from C code without any similar strange construct as DeviceStrategy function.

Next question, why you use far pointers if driver code is small/tiny model?
all internal pointers can be near.

**Comment by eduardocasino** [comment]
> I am not sure what you are trying to achive by DeviceStrategy function, but it is generaly wrong.
> 
> ```
> void __declspec(naked) far DeviceStrategy( void )
> {
>     __asm {
>         mov     word ptr cs:[fpRequest], bx
>         mov     word ptr cs:[fpRequest+2], es
>         retf
>     }
> }
> ```
> 
> What es:bx is? In C code it is random, not guarantie value. I thing it should be something like
> 
> ```
> static void _device_strategy( void far *req );
> #pragma aux _device_strategy = \
>         "mov     word ptr cs:[fpRequest], bx" \
>         "mov     word ptr cs:[fpRequest+2], es" \
>      parm [es bx]
> 
> void far DeviceStrategy( void far *req )
> {
>     _device_strategy( req );
> }
> ```
> 
> anyway you can use fpRequest directly in C code and need not to use DeviceStrategy at all. it is enough if you define fpRequest as
> 
> ```
> #define CODE_BASED    __based(segname("_CODE"))
> static request far * CODE_BASE fpRequest = (request far *)0;
> ```
> 
> this way you can define other variables located in code segment to be accessible directly from C code without any similar strange construct as DeviceStrategy function.

It is just the way device drivers work in DOS.

At org 0, there is the devive header structure::
```
        ; Device Header
        ;
        dd      -1                      ; Next device ( -1 == End of list )
        dw      DEVICE_ATTR
        dw      DeviceStrategy_
        dw      DeviceInterrupt_
        db      DEVICE_NAME
```
When DOS installs the driver, it adds this structure to a linked list of devices. Those devices can be opened like files using  `_dos_open()`  (Int 21/AH=3Dh ), you cad read and/or write to them and you can use functions Int 21/AX=44XXh to perform IOCTL operations.

Whenever you call one of those functions, the DOS kernel first calls the DeviceStrategy() routine with the es:bx pointing to the request structure. Inmediately after, calls the DeviceInterrupt() routine, which uses the info in the request to do the real job. 

> Next question, why you use far pointers if driver code is small/tiny model? all internal pointers can be near.

The driver code is tiny model, but the DeviceStrategy() and DeviceInterrupt() routines are __far to the DOS kernel and the request structure is __far to the driver.

**Comment by jmalak** [comment]
> > I am not sure what you are trying to achive by DeviceStrategy function, but it is generaly wrong.
> > ```
> > void __declspec(naked) far DeviceStrategy( void )
> > {
> >     __asm {
> >         mov     word ptr cs:[fpRequest], bx
> >         mov     word ptr cs:[fpRequest+2], es
> >         retf
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What es:bx is? In C code it is random, not guarantie value. I thing it should be something like
> > ```
> > static void _device_strategy( void far *req );
> > #pragma aux _device_strategy = \
> >         "mov     word ptr cs:[fpRequest], bx" \
> >         "mov     word ptr cs:[fpRequest+2], es" \
> >      parm [es bx]
> > 
> > void far DeviceStrategy( void far *req )
> > {
> >     _device_strategy( req );
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > anyway you can use fpRequest directly in C code and need not to use DeviceStrategy at all. it is enough if you define fpRequest as
> > ```
> > #define CODE_BASED    __based(segname("_CODE"))
> > static request far * CODE_BASE fpRequest = (request far *)0;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this way you can define other variables located in code segment to be accessible directly from C code without any similar strange construct as DeviceStrategy function.
> 
> It is just the way device drivers work in DOS.
> 
> At org 0, there is the devive header structure::
> 
> ```
>         ; Device Header
>         ;
>         dd      -1                      ; Next device ( -1 == End of list )
>         dw      DEVICE_ATTR
>         dw      DeviceStrategy_
>         dw      DeviceInterrupt_
>         db      DEVICE_NAME
> ```
> 
> When DOS installs the driver, it adds this structure to a linked list of devices. Those devices can be opened like files using `_dos_open()` (Int 21/AH=3Dh ), you cad read and/or write to them and you can use functions Int 21/AX=44XXh to perform IOCTL operations.
> 
> Whenever you call one of those functions, the DOS kernel first calls the DeviceStrategy() routine with the es:bx pointing to the request structure. Inmediately after, calls the DeviceInterrupt() routine, which uses the info in the request to do the real job.
> 
> > Next question, why you use far pointers if driver code is small/tiny model? all internal pointers can be near.
> 
> The driver code is tiny model, but the DeviceStrategy() and DeviceInterrupt() routines are __far to the DOS kernel and the request structure is __far to the driver.

OK, but who call DeviceStrategy and how?
If I understand it properly then code should be something like

```
/* prototype */
static void __far DeviceStrategy( void __far *req );
#pragma aux DeviceStrategy __parm [__es __bx]

/* definition */
void __far DeviceStrategy( void __far *req )
{
    fpRequest = req;
}
```
it expected indirect far call to DeviceStrategy (not interrupt) with es:bx as far pointer, not changing any register.

**Comment by eduardocasino** [comment]
> OK, but who call DeviceStrategy and how? If I understand it properly then code should be something like
> 
> ```
> /* prototype */
> static void __far DeviceStrategy( void __far *req );
> #pragma aux DeviceStrategy __parm [__es __bx]
> 
> /* definition */
> void __far DeviceStrategy( void __far *req )
> {
>     fpRequest = req;
> }
> ```
> 
> it expected indirect far call to DeviceStrategy (not interrupt) with es:bx as far pointer, not changing any register.

DeviceStrategy() is called by the DOS kernel itself and you undesrstood it perfectly :)

It just have to be public, not static, because it is referenced in cstrtsys.asm, and I think that using the request type definition would be even better:

```
void __far DeviceStrategy( request __far *req )
#pragma aux DeviceStrategy __parm [__es __bx]
{
    fpRequest = req;
}
```
On a side note, do you recommend using the __parm, __far, __es ... keywords over the parm, far, es ... macros?

Thank you!

**Comment by jmalak** [comment]
> > OK, but who call DeviceStrategy and how? If I understand it properly then code should be something like
> > ```
> > /* prototype */
> > static void __far DeviceStrategy( void __far *req );
> > #pragma aux DeviceStrategy __parm [__es __bx]
> > 
> > /* definition */
> > void __far DeviceStrategy( void __far *req )
> > {
> >     fpRequest = req;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it expected indirect far call to DeviceStrategy (not interrupt) with es:bx as far pointer, not changing any register.
> 
> DeviceStrategy() is called by the DOS kernel itself and you undesrstood it perfectly :)
> 
> It just have to be public, not static, because it is referenced in cstrtsys.asm, and I think that using the request type definition would be even better:
> 
> ```
> void __far DeviceStrategy( request __far *req )
> #pragma aux DeviceStrategy __parm [__es __bx]
> {
>     fpRequest = req;
> }
> ```
> 
> On a side note, do you recommend using the __parm, __far, __es ... keywords over the parm, far, es ... macros?
> 
> Thank you!

Generaly use of symbols with 2x undescore and starting lower case is reserved for compiler implementation and it is exactly this case.
It cannot clash with user macros for these words. Macros without 2x underscore can cause "very strange" problems if such macros is use somewhere, that use it with 2x undescore is much safer.

Anyway you could use for DeviceInterrupt following construct to have access to input/output registers from C code.
It could be based on "union INTPACK" structure which is defined in <i86.h> header file.

It could be something like

```
#define push_intpack_regs "push ax" "push cx" "push dx" "push bx" "push sp" "push bp" "push si" "push di"
#define push_intpack_retval "mov ax,ss" "mov dx,ax" "mov ax,sp" __value [__dx __ax]
#define pop_intpack_regs "pop di" "pop si" "pop bp" "pop bx" "pop bx" "pop dx" "pop cx" "pop ax"
#if defined( _M_IX86 >= 0x300 )
#define push_intpack_segreg "push ds" "push es" "push fs" "push gs"
#define pop_intpack_segregs "pop gs" "pop fs" "pop es" "pop ds"
#else
#define push_intpack_segregs "push ds" "push es" "push ax" "push ax"
#define pop_intpack_segregs "pop ax" "pop ax" "pop es" "pop ds"
#endif

extern union INTPACK __far  *push_intpack( void );
#pragma aux push_intpack = \
    "pushf" \
    push_intpack_regs \
    push_intpack_segregs \
    push_intpack_retval

extern void pop_intpack( void );
#pragma aux pop_intpack = \
    pop_intpack_segregs \
    pop_intpack_regs \
    "popf"

union INTPACK __far *r;

#pragma aux DeviceInterrupt __modify [__ax __bx __cx __dx __di __si __bp]
void __far DeviceInterrupt( void )
{
    r = push_intpack();
    if ( fpRequest->r_command > C_MAXCMD || NULL == (currentFunction = dispatchTable[fpRequest->r_command]) )
    {
        fpRequest->r_status = S_DONE | S_ERROR | E_CMD;
    }
    else
    {
        fpRequest->r_status = currentFunction();
    }
    pop_intpack();
}
```

**Comment by eduardocasino** [comment]
> Generaly use of symbols with 2x undescore and starting lower case is reserved for compiler implementation and it is exactly this case.
> It cannot clash with user macros for these words. Macros without 2x underscore can cause "very strange" problems if such macros is use somewhere, that use it with 2x undescore is much safer.

OK, thanks for the explanation. I'm going to follow your tip.

> Anyway you could use for DeviceInterrupt following construct to have access to input/output registers from C code.
> It could be based on "union INTPACK" structure which is defined in <i86.h> header file.

Yes, I thought about that, but all the information, input parameters and output values, is always passed in the request structure, so accessing the registers is not necessary. Also, by design, the device interrupt should not modify any register.

**Comment by jmalak** [comment]
> > Generaly use of symbols with 2x undescore and starting lower case is reserved for compiler implementation and it is exactly this case.
> > It cannot clash with user macros for these words. Macros without 2x underscore can cause "very strange" problems if such macros is use somewhere, that use it with 2x undescore is much safer.
> 
> OK, thanks for the explanation. I'm going to follow your tip.
> 
> > Anyway you could use for DeviceInterrupt following construct to have access to input/output registers from C code.
> > It could be based on "union INTPACK" structure which is defined in <i86.h> header file.
> 
> Yes, I thought about that, but all the information, input parameters and output values, is always passed in the request structure, so accessing the registers is not necessary. Also, by design, the device interrupt should not modify any register.

I am not familaire with DOS drivers, yes it has no sense for you.
But you could use push_intpack and pop_intpack instead of your __asm blocks that code is more readable and functionality is exactly same.

**Comment by eduardocasino** [comment]
> I am not familaire with DOS drivers, yes it has no sense for you.
> But you could use push_intpack and pop_intpack instead of your __asm blocks that code is more readable and functionality is exactly same.

No doubt about that and I'm following your advice. What I meant is that there is no need in accessing the resgisters in the C code, but the readability part, completely agree :)

**Comment by jmalak** [comment]
#pragma aux in-line code is more powerfull then __asm block.
by example #pragma aux can be used multiple time but __asm block no, you can define exact type of parameters if it is in register or on stack etc.
It is as template that you can have header file with many #pragma aux in-line code and simply use what you need only and it include only used part into generated code.
__asm has sense if you need "some" kind of portability to other compilers, but it is always limited.
